export const ReportFooter = () => {
  return (
    <div className="mt-8 text-center text-sm text-gray-500">
      <p>Generated by ChatSites AI Analysis Tool</p>
      <p>www.chatsites.ai</p>
    </div>
  );
};