import { Button } from "../ui/button";
import { Phone } from "lucide-react";

export const ReportFooter = () => {
  return (
    <div className="mt-12 space-y-6">
      <div className="text-center text-sm text-gray-500">
        <p>Generated by ChatSites AI Analysis Tool</p>
        <p>www.chatsites.ai</p>
      </div>
      <div className="flex flex-col items-center gap-4">
        <Button
          onClick={() => window.location.href = 'tel:8001234567'}
          className="bg-[#f65228] hover:bg-[#d43d16] text-white flex items-center gap-2"
        >
          <Phone className="h-4 w-4" />
          (800) 123-4567
        </Button>
        <p className="text-sm text-gray-600">
          Talk to Our AI Implementation Expert and Test the Magic
        </p>
      </div>
    </div>
  );
};