export const industries = [
  "Accounting & Tax Services",
  "Adult Care-Giver Agency",
  "Advertising & Marketing",
  "Agriculture",
  "Architecture & Design",
  "Automotive",
  "Banking & Financial Services",
  "Beauty Salon",
  "Business Consulting",
  "Child Daycare Services",
  "Construction",
  "Dental Practices",
  "E-commerce",
  "Education",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Event Planning",
  "Fashion & Apparel",
  "Finance",
  "Fitness & Wellness",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Holistic Medicine",
  "Home Services",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "Interior Design",
  "IT Services",
  "Legal Services",
  "Logistics",
  "Manufacturing",
  "Media",
  "Medical Practices",
  "Mining",
  "Non-Profit",
  "Pharmaceuticals",
  "Photography & Videography",
  "Professional Services",
  "Property Management",
  "Real Estate",
  "Recruitment",
  "Retail",
  "Security Services",
  "Software Development",
  "Spas",
  "Sports & Recreation",
  "Technology",
  "Telecommunications",
  "Tourism & Travel",
  "Transportation",
  "Utilities",
  "Veterinary Services",
  "Wholesale Distribution",
  "Other"
];