export const industries = [
  "Adult Care-Giver Agency",
  "Agriculture",
  "Automotive",
  "Beauty Salon",
  "Child Daycare Services",
  "Construction",
  "Education",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Finance",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Holistic Medicine",
  "Hospitality",
  "Insurance",
  "Legal Services",
  "Logistics",
  "Manufacturing",
  "Media",
  "Mining",
  "Non-Profit",
  "Pharmaceuticals",
  "Professional Services",
  "Real Estate",
  "Retail",
  "Spas",
  "Technology",
  "Telecommunications",
  "Transportation",
  "Utilities",
  "Other"
];