export const generateFooterSection = (doc: HTMLDivElement) => {
  const footer = document.createElement('div');
  footer.innerHTML = `
    <div style="text-align: center; color: #6B7280; font-size: 14px; margin-top: 40px; line-height: 1.5;">
      <p style="margin: 0 0 4px 0;">Generated by AI Analysis Tool</p>
      <p style="margin: 0;">www.chatsites.ai</p>
    </div>
  `;
  doc.appendChild(footer);
};