export const generateFooterSection = (doc: HTMLDivElement) => {
  const footer = document.createElement('div');
  footer.innerHTML = `
    <div style="text-align: center; margin-top: 32px;">
      <p style="color: #6B7280; font-size: 14px; margin: 0 0 4px 0;">Generated by ChatSites AI Analysis Tool</p>
      <p style="color: #6B7280; font-size: 14px; margin: 0;">www.chatsites.ai</p>
    </div>
  `;
  doc.appendChild(footer);
};